# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('home', models.CharField(max_length=255)),
                ('post_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('Num', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('edu', models.CharField(max_length=255)),
                ('pro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eval_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField(blank=True, max_length=300)),
                ('comp', models.CharField(max_length=255)),
                ('expertise', models.TextField(blank=True, max_length=300)),
                ('part', models.BooleanField()),
                ('retire', models.BooleanField()),
                ('job', models.CharField(max_length=255)),
                ('time_len', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('witness', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('q_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Re_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='expert_system.Expert')),
                ('agency', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('politic', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('intype', models.CharField(default='注册', max_length=255)),
                ('type_card', models.CharField(max_length=255)),
                ('card_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('capacity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='expert_system.Capacity')),
                ('field', models.CharField(max_length=255)),
                ('other', models.TextField(blank=True, max_length=300)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(max_length=255)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Certificate')),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Capacity'),
        ),
        migrations.AddField(
            model_name='job_exp',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Capacity'),
        ),
        migrations.AddField(
            model_name='eval_exp',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Capacity'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Contract'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Education'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Job'),
        ),
        migrations.AddField(
            model_name='re_company',
            name='evaluate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system.Evaluate'),
        ),
    ]
