# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='re_company',
            old_name='name',
            new_name='com_name',
        ),
    ]
